### ISSUE TITLE
Add Support for HTTP 1.1 Connections

### ISSUE THREAD

**Issue by joekiller** [buger/gor#318]
[HTTP 1.1 connections](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html) are by design persistent. The raw listener's message processing logic doesn't support Pipelining which limits Go Replay from being used where persistent connections are common such as back end services.

I'm interested in having this improved as I am dealing with persistent connections that may over the same stream:

- send multiple HTTP 1.1 requests within the listener's timeout period,
- send additional messages over the same stream after the initial message timeout, and/or
- utilize the [Connection: close](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.10) header.

I'm thinking to handle the pipeline a TCPMessage would probably be wrapper or give way to a HTTPStream. The syream would have a scanning function to pull requests out as they come over the stream and those would then be dispatched. It could resume midstream because it would scan for HTTP requests headers.

**Comment by buger** [comment]
Well, it should support HTTP/1.1, and it even includes tests for that, and possibly you hit some bugs. Can you provide some test case when it does not work for you?

> send multiple HTTP 1.1 requests within the listener's timeout period,
This timeout used only for a non-finished requests. It means: wait some time till we receive final packets. If requests if fully received (in the case of GET requests all headers are received, in the case of requests with bodies if content-length == body length), and `message.complete` is `true`, the request will be dispatched immediately and do not wait for the timeout. Since single HTTP/1.1 connection can't send multiple requests in parallel, this logic should work for most of the cases. It require some additional protection, for example, if we lost packet in the first message (and can't recover it), and we receiving the second message while the first one is not yet dispatched (because it is incomplete), we can get conflict. I will think how to handle such conflicts, but in most cases, multiple messages should work as expected. 

> send additional messages over the same stream after the initial message timeout
Not sure what you mean by additional messages. Gor does not have "stream" notion, and once the message is fully received it gets dispatched and deleted, some we can process next message from the same stream.

> utilize the Connection: close header.
I do not think it is possible, because as mentioned above there is no "stream" processing. But what probably make sense to do, is to remove "Connection: close" header from all messages, because when we are replaying them via HTTP, we do not maintain the same stream as the original one.

> we do not maintain the same stream as the original one.
This is one of the features I'm planning for the Pro version: keeping exactly same HTTP sessions while replaying traffic. Spawning separate HTTP worker for each HTTP session (we can define session ID as inbound_port+inbound_ip).

**Comment by joekiller** [comment]
Okay I'm going to take a closer look. I have a troublesome cap if you are
interested.

**Comment by buger** [comment]
Sure, send it

**Comment by joekiller** [comment]
I don't think this is the issue anymore. I think #319 was my real problem.

**Comment by buger** [comment]
Just released  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include support for replaying keep-alive sessions, keeping the same connection for all the recorded session messages.
