### ISSUE TITLE
dataOffset calculation doesn't account for options in TCP header

### ISSUE THREAD

**Issue by joekiller** [buger/gor#320]
if data offset > 5 then options will have padded bytes. [if len(data) > int(dataOffset*4)](https://github.com/buger/gor/blob/c756a11333905d39706180a6dd8245b9ee5f77d2/raw_socket_listener/listener.go#L419-L423)  assumes no option variables are sent. If options are being used, then the padding on the packet causes the replay to assume there is data on the packet with there is in fact none. I believe this is why I was seeing #319.

**Comment by buger** [comment]
Well from what I understand, in TCP packet data always starts at dataOffset*4 padding, and not depend if there are options field or not.

**Comment by buger** [comment]
@joekiller I think it should be fixed in master. It did not properly compute Seq for packets containing data when requests consist of multiple TCP packets.

Here are binaries:
[gor_100_continue_multi_packet_mac.tar.gz](https://github.com/buger/gor/files/343869/gor_100_continue_multi_packet_mac.tar.gz)
[gor_100_continue_multi_packet_x64.tar.gz](https://github.com/buger/gor/files/343868/gor_100_continue_multi_packet_x64.tar.gz)

**Comment by joekiller** [comment]
Nice catch. I think we are nailing 100-continue replay :)

**Comment by joekiller** [comment]
Fwiw I think the code accommodations offsets for the header correctly, it was the runt Ethernet frame messing with the data payload.

**Comment by buger** [comment]
Just released  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
