### ISSUE TITLE
--http-disallow-header equals --http-allow-header

### ISSUE THREAD

**Issue by lucaspouzac** [buger/gor#351]
Hi, 

If I try to filter traffic using --http-disallow-header option, it works much like the --http-allow-header option.

Version : 100_continue_multi_packet

Regards

**Comment by buger** [comment]
Hello! This is definitely was a typo! Fixed in master, here is binaries:
[gor_fix_http_disallow_header_mac.tar.gz](https://github.com/buger/gor/files/394273/gor_fix_http_disallow_header_mac.tar.gz)
[gor_fix_http_disallow_header_x64.tar.gz](https://github.com/buger/gor/files/394274/gor_fix_http_disallow_header_x64.tar.gz)

**Comment by lucaspouzac** [comment]
Thanks!

**Comment by buger** [comment]
New version  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
