### ISSUE TITLE
No 'raw_socket' interception engine in 0.15.1

### ISSUE THREAD

**Issue by Kooper** [buger/gor#366]
Hello,

Can't use 'raw_socket' as a parameter to input-raw-engine, although it is stated in documentation:

    $ sudo gor/0.15.1/gor --input-raw :8880 --output-http 127.0.0.1:8881  -input-raw-engine raw_socket
    2016/09/12 17:45:13 Unknown traffic interception engine:1

**Comment by buger** [comment]
I see, well I did not update documentation yet regarding this change, but I'm planning to remove raw socket at all because it is too hard to maintain and libpcap should work everywhere. 

If libpcap does not work for you, maybe it's better to try to fix it instead. Can you remind me your problem with libpcap? Thanks!

**Comment by Kooper** [comment]
There were no problems with libpcap :)

I came across strange doubling of requests to destination server and while debugging it switched to different capture mode. But it turned out that doubling requests were due to another forgotten docker container, running gor. So no problems with pcap, even in Docker environments..

Removing this mode from documentation seems enough.
