### ISSUE TITLE
"gor" name is too short, makes tool difficult to find

### ISSUE THREAD

**Issue by nkadel-skyhook** [buger/gor#401]
The name "gor" is so short that it is difficult to find via Google, and actually links to a great number of John Norman's "Gor" books. Please rename this tool, or at least rename the binary, to "goreplay".

**Comment by buger** [comment]
Well, actually one of the latest changes in the project was changing its name to "GoReplay". 

I did not touched binaries and Github name mostly because already had quite large user base, and wanted to avoid confusion. 

All the readme, docs and site use new "GoReplay" name. I will think about renaming Github project, from what I heard Github keeps aliases, so it should be quite safe.

**Comment by nkadel-skyhook** [comment]
Thank you. I've had good success with such github renames.
